apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-app
spec:
  replicas: 3  # Número de réplicas de tu aplicación
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-container
          image: ghcr.io/tu-usuario/hello:latest
          ports:
            - containerPort: 3000  # Puerto expuesto por el contenedor
          env:
            - name: NODE_ENV
              value: "production"  # Variables de entorno para la app
