apiVersion: v1
kind: Service
metadata:
  name: hello-dolly-service
spec:
  type: LoadBalancer  # Exponer el servicio usando un LoadBalancer
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 80  # Puerto en el cual el servicio estará disponible
      targetPort: 3000  # Puerto dentro del contenedor (el que la aplicación escucha)
